# Generated by Django 5.2.4 on 2025-07-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateField(verbose_name="Дата оплаты"),
        ),
    ]
