# Generated by Django 5.2.4 on 2025-07-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_payment_payment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                help_text="Введите имя пользователя",
                max_length=30,
                verbose_name="Имя пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                help_text="Введите фамилие пользователя",
                max_length=30,
                verbose_name="Фамилие пользователя",
            ),
        ),
    ]
