# Generated by Django 5.2.4 on 2025-07-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="Введите имя пользователя",
                max_length=30,
                null=True,
                verbose_name="Имя пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                help_text="Введите фамилие пользователя",
                max_length=30,
                null=True,
                verbose_name="Фамилие пользователя",
            ),
        ),
    ]
